2017-03-04 15:08:39 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO CLIENTS ('id'[*], 'name') VALUES (1, 'сбертех') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO CLIENTS ('id'[*], 'name') VALUES (1, 'сбертех') "; expected "identifier"; SQL statement:
INSERT INTO clients ('id', 'name') VALUES (1, 'сбертех') [42001-193]
2017-03-04 15:09:41 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO CLIENTS ('id'[*], 'name') VALUES ('1', 'сбертех') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO CLIENTS ('id'[*], 'name') VALUES ('1', 'сбертех') "; expected "identifier"; SQL statement:
INSERT INTO clients ('id', 'name') VALUES ('1', 'сбертех') [42001-193]
2017-03-04 15:17:09 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO CLIENTS ('id'[*], 'name') VALUES (11, 'сбертех') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO CLIENTS ('id'[*], 'name') VALUES (11, 'сбертех') "; expected "identifier"; SQL statement:
INSERT INTO clients ('id', 'name') VALUES (11, 'сбертех') [42001-193]
2017-03-04 15:19:57 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO CLIENTS ('id'[*], 'name') VALUES (11, 'сбертех') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO CLIENTS ('id'[*], 'name') VALUES (11, 'сбертех') "; expected "identifier"; SQL statement:
INSERT INTO clients ('id', 'name') VALUES (11, 'сбертех') [42001-193]
2017-03-04 15:23:19 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO CLIENTS ('id_advertisement'[*], 'name') VALUES (11, 'сбертех') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO CLIENTS ('id_advertisement'[*], 'name') VALUES (11, 'сбертех') "; expected "identifier"; SQL statement:
INSERT INTO clients ('id_advertisement', 'name') VALUES (11, 'сбертех') [42001-193]
2017-03-04 15:23:46 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Синтаксическая ошибка в выражении SQL "INSERT INTO CLIENTS ('id_advertisement'[*], 'name') VALUES (11, 'сбертех') "; ожидалось "identifier"
Syntax error in SQL statement "INSERT INTO CLIENTS ('id_advertisement'[*], 'name') VALUES (11, 'сбертех') "; expected "identifier"; SQL statement:
INSERT INTO clients ('id_advertisement', 'name') VALUES (11, 'сбертех') [42001-193]
2017-03-07 14:57:07 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDERS" already exists; SQL statement:
CREATE TABLE orders ( id BIGINT NOT NULL, amount DOUBLE, description VARCHAR(1024), idClient BIGINT, idContact BIGINT, PRIMARY KEY (id), FOREIGN KEY (idClient) REFERENCES clients ) [42101-193]
2017-03-07 15:39:01 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDERS" already exists; SQL statement:
CREATE TABLE orders ( id BIGINT NOT NULL, amount DOUBLE, description VARCHAR(1024), idClient BIGINT, idContact BIGINT, PRIMARY KEY (id), FOREIGN KEY (idClient) REFERENCES clients, FOREIGN KEY (idContact) REFERENCES contacts ) [42101-193]
2017-03-07 15:39:58 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDERS" already exists; SQL statement:
CREATE TABLE orders ( id BIGINT NOT NULL, amount DOUBLE, description VARCHAR(1024), idClient BIGINT, idContact BIGINT, PRIMARY KEY (id), FOREIGN KEY (idClient) REFERENCES clients, FOREIGN KEY (idContact) REFERENCES contacts ) [42101-193]
2017-03-08 10:13:44 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDERSTOCONTACTSBINDING" not found; SQL statement:
DROP TABLE ordersToContactsBinding [42102-193]
2017-03-08 10:17:23 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1483)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1458)
	at org.h2.jdbc.JdbcConnection.createStatement(JdbcConnection.java:202)
	at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:525)
	at org.apache.tomcat.jdbc.pool.PooledConnection.validate(PooledConnection.java:443)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:799)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:648)
	at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:198)
	at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:132)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
	at org.hibernate.tool.hbm2ddl.SuppliedConnectionProviderConnectionHelper.prepare(SuppliedConnectionProviderConnectionHelper.java:33)
	at org.hibernate.tool.hbm2ddl.DatabaseExporter.<init>(DatabaseExporter.java:35)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:425)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:375)
	at org.hibernate.tool.hbm2ddl.SchemaExport.drop(SchemaExport.java:371)
	at org.hibernate.internal.SessionFactoryImpl.close(SessionFactoryImpl.java:1081)
	at org.hibernate.jpa.internal.EntityManagerFactoryImpl.close(EntityManagerFactoryImpl.java:347)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.invokeProxyMethod(AbstractEntityManagerFactoryBean.java:459)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean$ManagedEntityManagerFactoryInvocationHandler.invoke(AbstractEntityManagerFactoryBean.java:630)
	at com.sun.proxy.$Proxy82.close(Unknown Source)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.destroy(AbstractEntityManagerFactoryBean.java:550)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:272)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009)
	at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:928)
2017-03-08 10:17:39 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDERSTOCONTACTSBINDING" already exists; SQL statement:
CREATE TABLE ordersToContactsBinding ( id BIGINT NOT NULL, idOrder BIGINT NOT NULL, idContact BIGINT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (idOrder) REFERENCES orders, FOREIGN KEY (idContact) REFERENCES contacts ) [42101-193]
2017-03-08 10:19:24 jdbc[12]: exception
org.h2.jdbc.JdbcSQLException: Table "ORDERS" already exists; SQL statement:
CREATE TABLE orders ( id BIGINT NOT NULL, amount DOUBLE, description VARCHAR(1024), idClient BIGINT, idContact BIGINT, PRIMARY KEY (id), FOREIGN KEY (idClient) REFERENCES clients, FOREIGN KEY (idContact) REFERENCES contacts ) [42101-193]
